site_name: Python cursus
site_url: https://HappySteltral.github.io/Cursus-Python/
theme:
  name: material
  language: nl

nav:
  - Start: index.md
  - Cursus:    
    - Stap 1 Expressies: cursus/01_expressies/stap_1_expressies.md
    - Stap 2 Basis: cursus/02_variabelen/variabelen.md
    - Stap 3 Input en output: cursus/03_input_output/stap_3_input_en_output.md
    - Stap 4 Beslissingen: cursus/04_beslissingen/stap_4_beslissingen.md
  - Opgavenbank:
    # - overzicht: opgaven/index.md
    - Python Basis:
      - Variabelen : opgaven/python_basis/basis_oefeningen_stap_1_variabelen.md
      - Expressies : opgaven/python_basis/basis_oefeningen_stap_2_expressies.md 
    #  5 ICW:
    #       - Basis: opgaven/5ICW/basis.md
    # - 6 ICW:
    #       - Uitdaging: opgaven/6ICW/uitdaging.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences